### ISSUE TITLE
cmd-shift-d appears to conflict with "bookmark all tabs" on osx

### ISSUE THREAD

**Issue by escapewindow** [jonathanKingston/new-container-tab#1]

**Comment by jonathanKingston** [comment]
Does this actually prevent it working?

If you could think of something better that isn't taken:

Visit:
https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly?redirectlocale=en-US&as=u&redirectslug=Keyboard+shortcuts&utm_source=inproduct

In console run:
```
document.querySelectorAll("[data-for]").forEach(e => e.style.display = "block"); const sheet = document.createElement("style"); sheet.innerText=`[data-for]::before {display: block; font-weight: bold;} [data-for~=linux]::before {content: "Linux: ";} [data-for~=mac]::before {content: "Mac: ";} [data-for~=win]::before {content: "Windows: ";} [data-for~=win]::before, [data-for~=linux]::before {content: "Windows + Linux: ";}`; document.body.appendChild(sheet);
```

Ideally we should have a shortcut that matches all OSs.

There is also limitations on top of that list based on the native OS too which makes the list even smaller.

My preferred choice would be `Ctrl + T` to override the default with the ability for the user to change it however this isn't possible.

**Comment by escapewindow** [comment]
> Does this actually prevent it working?

Yes, it pops up the "bookmark all tabs" menu item when I hit cmd-shift-d.

> My preferred choice would be Ctrl + T to override the default with the ability for the user to change it however this isn't possible.

Me too.

**Comment by escapewindow** [comment]
cmd-shift-x and cmd-shift-f seem unclaimed on the left hand side of a qwerty keyboard, as are cmd-shift-` (tilde) and cmd-shift-5.

**Comment by escapewindow** [comment]
Avoiding cmd-shift-e because if tab groups ever comes back, that's tab groups.

**Comment by falolaf** [comment]
and ctrl+shift+D conflicts with "bookmark all tabs", in this case on Windows 7. (Should I open another issue?)

**Comment by jonathanKingston** [comment]
Sounds like this might be a bug for Linux then. Will try if either of these
suggestions work in web extensions work later.

**Comment by jonathanKingston** [comment]
I'm going to change this to Alt+C as it seems this works everywhere

**Comment by falolaf** [comment]
Seems to work. Tested on FF55, Win7.

The shortcut clashes with another addon though: Containers On The Go...

**Comment by jonathanKingston** [comment]
Yeah I'm aware of the clash which is a reason I used it:
- good shortcuts are near impossible to find
- both extensions are different and containers on the go has buttons and
other context menus too.
- long term Firefox should allow reallocation of shortcuts

So despite this being annoying I'm not sure there is an obvious alternative.

**Comment by dandavison** [comment]
> My preferred choice would be Ctrl + T

Just in case it's helpful for MacOS users, I was able to get the default newtab keybinding, Command+T, to open a new container tab by using this browser extension, and using [karabiner](https://pqrs.org/osx/karabiner/) to remap Command+T to Alt+C system-wide. Of course, you have to be OK with remapping that system wide. To do the key remapping in karabiner, add the following as the contents of a JSON file under `~/.config/karabiner/assets/complex_modifications/`, and then use "Complex Modifications" => "Add rule" within the Karabiner-Elements app.

```json
{
  "title": "Use left_command+t to issue alt+c to override newtab behavior in firefox.",
  "rules": [
    {
      "description": "Use left_command+t to issue alt+c to override newtab behavior in firefox.",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "t",
            "modifiers": {
              "mandatory": [
                "left_command"
              ]
            }
          },
          "to": [
            {
              "key_code": "c",
              "modifiers": [
                "left_option"
              ]
            }
          ]
        }
      ]
    }
  ]
}
```
